server:
  port: 8090

debug: true

logging:
  level:
    com: debug

date:
  pattern: yyyy-MM-dd HH:mm

management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics

minfin:
  gas: https://index.minfin.com.ua/ua/tariff/gas/

spring:
  data:
    mongodb:
      database: ${DBNAME}
      host: ${DBHOST}
      password: ${DBPASS}
      port: ${DBPORT}
      username: ${DBUSER}

application:
  stackTraceEnabled: true
